#!/bin/bash
# Generate src/Version.hs with build metadata.
# Uses git if available, falls back to GIT_HASH/GIT_TAG/BUILD_TARGET env vars.
set -e

cd "$(dirname "$0")"

GIT_HASH="${GIT_HASH:-$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")}"
# Append -dirty if working tree is dirty (only when git is available)
if [ "$GIT_HASH" != "unknown" ] && git rev-parse --git-dir >/dev/null 2>&1; then
    git diff --quiet HEAD 2>/dev/null || GIT_HASH="${GIT_HASH}-dirty"
fi
GIT_TAG="${GIT_TAG:-$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")}"
VERSION=$(grep "^version:" volca.cabal | awk '{print $2}')
BUILD_TARGET="${BUILD_TARGET:-linux}"

cat > src/Version.hs << EOF
-- AUTO-GENERATED by gen-version.sh -- do not edit
module Version where

version, gitHash, gitTag, buildTarget :: String
version = "$VERSION"
gitHash = "$GIT_HASH"
gitTag = "$GIT_TAG"
buildTarget = "$BUILD_TARGET"
EOF

echo "Generated src/Version.hs (hash=$GIT_HASH, target=$BUILD_TARGET)"
