"""VoLCA Python client — Life Cycle Assessment engine.

See https://volca.run/docs/guides/pyvolca/ for the full guide.
"""

from ._download import DownloadError, Installed, download
from .client import Client, VoLCAError
from .compare import ActivityDiff, ActivityDiffRow, compare_activities
from .server import Server
from .types import (
    Activity,
    ActivityContribution,
    ActivityDetail,
    AggregateGroup,
    AggregateOp,
    AggregateResult,
    AggregateScope,
    BioDirection,
    BiosphereExchange,
    CharacterizationFactor,
    CharacterizationResult,
    ClassificationFilter,
    ClassificationSystem,
    Compartment,
    ConsumerResult,
    ConsumersResponse,
    ContributingActivities,
    ContributingFlows,
    DatabaseInfo,
    DatabaseStatus,
    Exchange,
    Flow,
    FlowContribution,
    FlowMapping,
    FlowMappingEntry,
    InventoryFlow,
    InventoryResult,
    InventoryStatistics,
    LCIABatchResult,
    LCIAResult,
    MatchMode,
    Method,
    PathResult,
    PathStep,
    Preset,
    PresetFilter,
    ScoringIndicator,
    SearchResults,
    ServerVersion,
    Substitution,
    SupplyChain,
    SupplyChainEdge,
    SupplyChainEntry,
    TechRole,
    TechnosphereExchange,
    WasteExchange,
)

__all__ = [
    "Activity",
    "ActivityContribution",
    "ActivityDetail",
    "ActivityDiff",
    "ActivityDiffRow",
    "AggregateGroup",
    "AggregateOp",
    "AggregateResult",
    "AggregateScope",
    "BioDirection",
    "BiosphereExchange",
    "CharacterizationFactor",
    "CharacterizationResult",
    "Client",
    "ClassificationFilter",
    "ClassificationSystem",
    "Compartment",
    "ConsumerResult",
    "ConsumersResponse",
    "ContributingActivities",
    "ContributingFlows",
    "DatabaseInfo",
    "DatabaseStatus",
    "DownloadError",
    "Exchange",
    "Flow",
    "FlowContribution",
    "FlowMapping",
    "FlowMappingEntry",
    "Installed",
    "InventoryFlow",
    "InventoryResult",
    "InventoryStatistics",
    "LCIABatchResult",
    "LCIAResult",
    "MatchMode",
    "Method",
    "PathResult",
    "PathStep",
    "Preset",
    "PresetFilter",
    "ScoringIndicator",
    "SearchResults",
    "Server",
    "ServerVersion",
    "Substitution",
    "SupplyChain",
    "SupplyChainEdge",
    "SupplyChainEntry",
    "TechRole",
    "TechnosphereExchange",
    "VoLCAError",
    "WasteExchange",
    "compare_activities",
    "download",
]
