"""Generate type stubs from a VoLCA OpenAPI spec.

This module is pyvolca's answer to the "decouple client release cadence
from engine API changes" problem. Hand-written wrappers in
:mod:`volca.client` already provide typed signatures for the hot paths;
this module adds autocomplete coverage for *every* operation the engine
exposes, including new ones added after the installed pyvolca was
released.

The generated stub file (``_operations.pyi``) is written into the
installed pyvolca package directory, where mypy and pyright pick it up
automatically — no ``MYPYPATH`` plumbing required.

Trigger points
--------------
- :meth:`volca.client.Client.refresh_stubs` — fetches
  ``/api/v1/openapi.json`` from a running server and regenerates.
- :func:`write_stubs_for_spec` — the pure function; takes an already-fetched
  spec dict. Useful for CI, offline generation, and tests.

Stubs vs. the real class
------------------------
The generated file declares a ``_Operations`` Protocol with one ``def``
per operationId. This doesn't replace :class:`Client`; the client's
hand-written wrappers remain the authoritative API surface. The stub
only adds type info for the generic ``call(operation_id, **kwargs)``
escape hatch via a companion overload, letting IDEs auto-complete
``client.call("get_impacts", process_id=..., method_id=...)`` with the
correct parameter list.

The stub is intentionally minimal — no dataclass return types, just
``Any`` — because the full type hierarchy is ecosystem-specific (Pydantic
vs. dataclass vs. TypedDict) and pyvolca's hand-written wrappers already
cover the return-type story for the hot paths.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any


_STUB_HEADER = '''"""Auto-generated type stubs for pyvolca — do NOT edit by hand.

Regenerated by :func:`volca._stub_gen.write_stubs_for_spec`, typically
via :meth:`volca.client.Client.refresh_stubs`. See that module for when
and why regeneration happens.

The stubs mirror the OpenAPI spec served by a specific VoLCA engine
build. Installing a newer engine and calling ``refresh_stubs()`` will
overwrite this file with that engine's operation list.
"""

from typing import Any, Literal, Protocol, overload


class _Operations(Protocol):
    """Every operation exposed by the engine this stub was generated from.

    Consumed by the overloaded :meth:`volca.client.Client.call` stubs below,
    giving IDE autocomplete on the operation_id literal and its kwargs.
    """
'''


def _py_type_for(schema: dict[str, Any] | None) -> str:
    """Best-effort JSON Schema → Python type hint.

    Falls back to ``Any`` for anything non-trivial. This is autocomplete
    material, not a type-safety contract.
    """
    if not schema:
        return "Any"
    t = schema.get("type")
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = _py_type_for(schema.get("items"))
        return f"list[{items}]"
    return "Any"


def _snake_from_wire(wire_name: str) -> str:
    """Inverse of :func:`volca.client._candidate_wire_names` — produce a
    Python-idiomatic kwarg name for a wire-level parameter.

    ``processId`` → ``process_id``
    ``min-quantity`` → ``min_quantity``
    ``top-flows`` → ``top_flows``
    """
    # camelCase → snake_case
    out_chars: list[str] = []
    for ch in wire_name:
        if ch.isupper():
            if out_chars:
                out_chars.append("_")
            out_chars.append(ch.lower())
        elif ch == "-":
            out_chars.append("_")
        else:
            out_chars.append(ch)
    return "".join(out_chars)


def _render_operation(op_id: str, op_spec: dict[str, Any]) -> str:
    """Render one ``@overload def call(...)`` stub for a single operation."""
    params = op_spec.get("parameters", [])
    lines: list[str] = []
    lines.append("    @overload")
    lines.append("    def call(")
    lines.append("        self,")
    lines.append(f'        operation_id: Literal["{op_id}"],')
    lines.append("        *,")
    # db_name is auto-injected by Client but we still list it as optional
    # so IDE users can see it exists.
    injected_db = any(p.get("name") == "dbName" for p in params)
    if injected_db:
        lines.append("        db_name: str | None = ...,")
    for p in params:
        wire = p.get("name", "")
        if wire == "dbName":
            continue  # handled above
        py = _snake_from_wire(wire)
        py_type = _py_type_for(p.get("schema"))
        required = p.get("required", False)
        default = "" if required else " = ..."
        lines.append(f"        {py}: {py_type}{default},")
    # Substitutions is a universal escape hatch.
    lines.append("        substitutions: list[dict] | None = ...,")
    lines.append("    ) -> Any: ...")
    return "\n".join(lines)


def render_stub(spec: dict[str, Any]) -> str:
    """Build the full `.pyi` text from an OpenAPI spec."""
    operations: list[tuple[str, dict[str, Any]]] = []
    for path, item in sorted(spec.get("paths", {}).items()):
        for method, op_spec in item.items():
            if not isinstance(op_spec, dict):
                continue
            op_id = op_spec.get("operationId")
            if op_id:
                operations.append((op_id, op_spec))

    # Stable ordering so diffs are minimal across regenerations.
    operations.sort(key=lambda kv: kv[0])

    body: list[str] = []
    for op_id, op_spec in operations:
        body.append(_render_operation(op_id, op_spec))
    if not body:
        body.append("    pass  # no operations indexed")
    return _STUB_HEADER + "\n\n".join(body) + "\n"


def write_stubs_for_spec(
    spec: dict[str, Any],
    target: os.PathLike[str] | str | None = None,
) -> Path:
    """Render stubs and write them to the installed pyvolca package directory.

    Args:
        spec: An OpenAPI 3 spec dict (as returned by
            ``Client._load_operations`` or read from
            ``GET /api/v1/openapi.json``).
        target: Optional override for where to write. Defaults to
            ``<installed pyvolca dir>/_operations.pyi``. Useful for tests.

    Returns:
        The path the stub was written to.

    Raises:
        PermissionError: if the installed package directory is read-only
            (rare, but can happen in locked-down deployments). The caller
            may fall back to ``~/.cache/volca/stubs/`` and add it to
            ``MYPYPATH``.
    """
    text = render_stub(spec)
    if target is None:
        # Write alongside this module in the installed package directory.
        here = Path(__file__).resolve().parent
        target = here / "_operations.pyi"
    target_path = Path(target)
    target_path.write_text(text, encoding="utf-8")
    return target_path


if __name__ == "__main__":
    # Convenience: `python -m volca._stub_gen <spec.json>` regenerates
    # stubs from a committed spec file. Useful for CI and for offline
    # workflows.
    if len(sys.argv) != 2:
        print("Usage: python -m volca._stub_gen <openapi.json>", file=sys.stderr)
        sys.exit(2)
    import json
    with open(sys.argv[1], encoding="utf-8") as fh:
        spec = json.load(fh)
    path = write_stubs_for_spec(spec)
    print(f"wrote {path}")
